TRUNCATE TABLE SAMPLE_ENTITY;

INSERT INTO SAMPLE_ENTITY (id, name) VALUES (1, 'サンプルデータ1');
INSERT INTO SAMPLE_ENTITY (id, name) VALUES (2, 'サンプルデータ2');
INSERT INTO SAMPLE_ENTITY (id, name) VALUES (3, 'サンプルデータ3');