#!/bin/ksh
# パスワード取得コマンド
GET_PASSWORD_COMMAND="sudo /sbi/kbn/bin/getpwd2"

#
# 抽出元データベース接続情報
#

# データベース名
#EXPORT_DATABASE=DB1NON1R
EXPORT_DATABASE=SAMPLE

# スキーマ名
#EXPORT_SCHEMA=NFSUSR10
EXPORT_SCHEMA=DB2INST1

# ユーザー名
EXPORT_USER=db2inst1

# パスワード
EXPORT_PASSWORD=changeme

#
# 挿入先データベース接続情報
#
# TODO インポート先は要確認 & 動作確認完了後にコメント解除
# データベース名
#IMPORT_DATABASE=DBTNON8R
# スキーマ名
#IMPORT_SCHEMA=NFSUSR10
# ユーザー名
#IMPORT_USER=nfsusr10
# パスワード
#IMPORT_PASSWORD=nfsusr10

